[package]
name    = "aeris-daemon"
version = { workspace = true }
edition = { workspace = true }
publish = { workspace = true }

[[bin]]
name = "aerisd"
path = "src/main.rs"

[dependencies]
aeris-std          = { workspace = true }
rayon              = { workspace = true }
tokio              = { workspace = true, features = ["macros", "net"] }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
