[package]
name    = "aeris-cli"
version = { workspace = true }
edition = { workspace = true }
publish = { workspace = true }

[[bin]]
name = "aeris"
path = "src/main.rs"

[dependencies]
aeris-std = { workspace = true }
clap      = { workspace = true, features = ["derive"] }
tokio     = { workspace = true, features = ["full"] }
tracing   = { workspace = true }
