[package]
name    = "aeris-standard-ui-server"
edition = { workspace = true }
publish = { workspace = true }

[dependencies]
aeris-standard = { workspace = true }
clap           = { workspace = true, features = ["derive"] }
rayon          = { workspace = true }
tokio          = { workspace = true, features = ["full"] }
