[package]
name    = "aeris-standard_ui-server"
version = "0.1.0"
edition = { workspace = true }
publish = { workspace = true }

[dependencies]
aeris-standard = { workspace = true }
anyhow         = { workspace = true }
clap           = { workspace = true }
rayon          = { workspace = true }
tokio          = { workspace = true }
