[workspace]
resolver = "3"
members = [
  # AERIS
  "core",
  "core/ui",
  "core/ui/lib",
  "core/ui/macro",
  "core/code",

  # AERIS Standard
  "standard/core",
  "standard/core/ui",
  "standard/core/code",
  "standard/ui-server",
  "standard/cli",
]

[workspace.package]
edition = "2024"
publish = false

[workspace.dependencies]
aeris               = { path = "core" }
aeris-ui            = { path = "core/ui" }
aeris-ui-lib        = { path = "core/ui/lib" }
aeris-ui-macro      = { path = "core/ui/macro" }
aeris-code          = { path = "core/code" }
aeris-standard      = { path = "standard/core" }
aeris-standard-ui   = { path = "standard/core/ui" }
aeris-standard-code = { path = "standard/core/code" }
clap                = { version = "4" }
icu_properties      = { version = "2" }
inkwell             = { version = "0.8" }
proc-macro2         = { version = "1" }
quote               = { version = "1" }
rayon               = { version = "1" }
tokio               = { version = "1" }
