[workspace]
resolver = "3"
members  = ["core", "cli", "ui-server"]

[workspace.package]
edition = "2024"
publish = false

[workspace.dependencies]
aeris          = { path = "core" }
clap           = { version = "4" }
icu_properties = { version = "2" }
inkwell        = { version = "0.8" }
rayon          = { version = "1" }
tokio          = { version = "1" }
