[package]
name    = "aeris_standard_core"
edition = "2024"
publish = false

[dependencies]
inkwell            = { version = "0.6", features = ["llvm18-1"] }
unicode-properties = { version = "0.1" }
uuid               = { version = "1.18", features = ["v4"] }
