volumes:
  target:


services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ..:/workspaces/aeris:cached
      - target:/workspaces/aeris/target:cached
    command: sleep infinity
