volumes:
  target:


services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/aeris:cached
      - target:/workspaces/aeris/target:cached
    command: sleep infinity
