[package]
name    = "aeris-standard-core"
edition = "2024"
publish = false

[dependencies]
aeris          = { path = "../../core" }
icu_properties = { version = "2.0" }
uuid           = { version = "1.18", features = ["v4"] }
