[package]
name    = "example-json-cluster-postproc"
version = { workspace = true }
edition = { workspace = true }
publish = { workspace = true }

[lib]
proc-macro = true

[dependencies]
aeris = { workspace = true }

[build-dependencies]
aeris                = { workspace = true }
example-json-cluster = { workspace = true, features = ["preprocess"] }
