name: CI

on:
  pull_request:

permissions:
  packages: write

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - run: cargo clippy --workspace --locked --all-targets --all-features -- -D warnings

  test:
    needs: [fmt, clippy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-ci
          cacheFrom: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-ci
          push: always
          runCmd: cargo test --workspace --locked --all-features
