[package]
name    = "aeris-ui-proc"
version = { workspace = true }
edition = { workspace = true }
publish = { workspace = true }

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote       = { workspace = true }
rustc-hash  = { workspace = true }
syn         = { workspace = true, features = ["extra-traits"] }
